INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1101', '11', 'Kab. Simeulue');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1102', '11', 'Kab. Aceh Singkil');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1103', '11', 'Kab. Aceh Selatan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1104', '11', 'Kab. Aceh Tenggara');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1105', '11', 'Kab. Aceh Timur');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1106', '11', 'Kab. Aceh Tengah');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1107', '11', 'Kab. Aceh Barat');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1108', '11', 'Kab. Aceh Besar');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1109', '11', 'Kab. Pidie');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1110', '11', 'Kab. Bireuen');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1111', '11', 'Kab. Aceh Utara');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1112', '11', 'Kab. Aceh Barat Daya');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1113', '11', 'Kab. Gayo Lues');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1114', '11', 'Kab. Aceh Tamiang');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1115', '11', 'Kab. Nagan Raya');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1116', '11', 'Kab. Aceh Jaya');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1117', '11', 'Kab. Bener Meriah');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1118', '11', 'Kab. Pidie Jaya');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1171', '11', 'Kota Banda Aceh');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1172', '11', 'Kota Sabang');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1173', '11', 'Kota Langsa');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1174', '11', 'Kota Lhokseumawe');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1175', '11', 'Kota Subulussalam');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1201', '12', 'Kab. Nias');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1202', '12', 'Kab. Mandailing Natal');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1203', '12', 'Kab. Tapanuli Selatan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1204', '12', 'Kab. Tapanuli Tengah');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1205', '12', 'Kab. Tapanuli Utara');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1206', '12', 'Kab. Toba Samosir');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1207', '12', 'Kab. Labuhan Batu');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1208', '12', 'Kab. Asahan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1209', '12', 'Kab. Simalungun');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1210', '12', 'Kab. Dairi');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1211', '12', 'Kab. Karo');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1212', '12', 'Kab. Deli Serdang');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1213', '12', 'Kab. Langkat');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1214', '12', 'Kab. Nias Selatan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1215', '12', 'Kab. Humbang Hasundutan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1216', '12', 'Kab. Pakpak Bharat');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1217', '12', 'Kab. Samosir');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1218', '12', 'Kab. Serdang Bedagai');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1219', '12', 'Kab. Batu Bara');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1220', '12', 'Kab. Padang Lawas Utara');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1221', '12', 'Kab. Padang Lawas');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1222', '12', 'Kab. Labuhan Batu Selatan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1223', '12', 'Kab. Labuhan Batu Utara');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1224', '12', 'Kab. Nias Utara');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1225', '12', 'Kab. Nias Barat');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1271', '12', 'Kota Sibolga');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1272', '12', 'Kota Tanjung Balai');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1273', '12', 'Kota Pematang Siantar');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1274', '12', 'Kota Tebing Tinggi');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1275', '12', 'Kota Medan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1276', '12', 'Kota Binjai');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1277', '12', 'Kota Padangsidimpuan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1278', '12', 'Kota Gunungsitoli');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1301', '13', 'Kab. Kepulauan Mentawai');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1302', '13', 'Kab. Pesisir Selatan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1303', '13', 'Kab. Solok');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1304', '13', 'Kab. Sijunjung');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1305', '13', 'Kab. Tanah Datar');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1306', '13', 'Kab. Padang Pariaman');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1307', '13', 'Kab. Agam');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1308', '13', 'Kab. Lima Puluh Kota');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1309', '13', 'Kab. Pasaman');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1310', '13', 'Kab. Solok Selatan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1311', '13', 'Kab. Dharmasraya');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1312', '13', 'Kab. Pasaman Barat');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1371', '13', 'Kota Padang');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1372', '13', 'Kota Solok');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1373', '13', 'Kota Sawah Lunto');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1374', '13', 'Kota Padang Panjang');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1375', '13', 'Kota Bukittinggi');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1376', '13', 'Kota Payakumbuh');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1377', '13', 'Kota Pariaman');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1401', '14', 'Kab. Kuantan Singingi');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1402', '14', 'Kab. Indragiri Hulu');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1403', '14', 'Kab. Indragiri Hilir');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1404', '14', 'Kab. Pelalawan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1405', '14', 'Kab. S I A K');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1406', '14', 'Kab. Kampar');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1407', '14', 'Kab. Rokan Hulu');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1408', '14', 'Kab. Bengkalis');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1409', '14', 'Kab. Rokan Hilir');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1410', '14', 'Kab. Kepulauan Meranti');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1471', '14', 'Kota Pekanbaru');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1473', '14', 'Kota D U M A I');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1501', '15', 'Kab. Kerinci');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1502', '15', 'Kab. Merangin');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1503', '15', 'Kab. Sarolangun');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1504', '15', 'Kab. Batang Hari');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1505', '15', 'Kab. Muaro Jambi');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1506', '15', 'Kab. Tanjung Jabung Timur');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1507', '15', 'Kab. Tanjung Jabung Barat');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1508', '15', 'Kab. Tebo');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1509', '15', 'Kab. Bungo');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1571', '15', 'Kota Jambi');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1572', '15', 'Kota Sungai Penuh');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1601', '16', 'Kab. Ogan Komering Ulu');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1602', '16', 'Kab. Ogan Komering Ilir');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1603', '16', 'Kab. Muara Enim');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1604', '16', 'Kab. Lahat');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1605', '16', 'Kab. Musi Rawas');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1606', '16', 'Kab. Musi Banyuasin');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1607', '16', 'Kab. Banyu Asin');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1608', '16', 'Kab. Ogan Komering Ulu Selatan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1609', '16', 'Kab. Ogan Komering Ulu Timur');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1610', '16', 'Kab. Ogan Ilir');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1611', '16', 'Kab. Empat Lawang');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1671', '16', 'Kota Palembang');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1672', '16', 'Kota Prabumulih');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1673', '16', 'Kota Pagar Alam');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1674', '16', 'Kota Lubuklinggau');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1701', '17', 'Kab. Bengkulu Selatan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1702', '17', 'Kab. Rejang Lebong');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1703', '17', 'Kab. Bengkulu Utara');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1704', '17', 'Kab. Kaur');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1705', '17', 'Kab. Seluma');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1706', '17', 'Kab. Mukomuko');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1707', '17', 'Kab. Lebong');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1708', '17', 'Kab. Kepahiang');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1709', '17', 'Kab. Bengkulu Tengah');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1771', '17', 'Kota Bengkulu');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1801', '18', 'Kab. Lampung Barat');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1802', '18', 'Kab. Tanggamus');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1803', '18', 'Kab. Lampung Selatan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1804', '18', 'Kab. Lampung Timur');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1805', '18', 'Kab. Lampung Tengah');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1806', '18', 'Kab. Lampung Utara');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1807', '18', 'Kab. Way Kanan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1808', '18', 'Kab. Tulangbawang');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1809', '18', 'Kab. Pesawaran');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1810', '18', 'Kab. Pringsewu');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1811', '18', 'Kab. Mesuji');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1812', '18', 'Kab. Tulang Bawang Barat');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1813', '18', 'Kab. Pesisir Barat');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1871', '18', 'Kota Bandar Lampung');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1872', '18', 'Kota Metro');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1901', '19', 'Kab. Bangka');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1902', '19', 'Kab. Belitung');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1903', '19', 'Kab. Bangka Barat');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1904', '19', 'Kab. Bangka Tengah');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1905', '19', 'Kab. Bangka Selatan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1906', '19', 'Kab. Belitung Timur');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('1971', '19', 'Kota Pangkal Pinang');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('2101', '21', 'Kab. Karimun');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('2102', '21', 'Kab. Bintan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('2103', '21', 'Kab. Natuna');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('2104', '21', 'Kab. Lingga');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('2105', '21', 'Kab. Kepulauan Anambas');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('2171', '21', 'Kota B A T A M');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('2172', '21', 'Kota Tanjung Pinang');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3101', '31', 'Kab. Kepulauan Seribu');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3171', '31', 'Kota Jakarta Selatan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3172', '31', 'Kota Jakarta Timur');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3173', '31', 'Kota Jakarta Pusat');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3174', '31', 'Kota Jakarta Barat');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3175', '31', 'Kota Jakarta Utara');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3201', '32', 'Kab. Bogor');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3202', '32', 'Kab. Sukabumi');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3203', '32', 'Kab. Cianjur');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3204', '32', 'Kab. Bandung');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3205', '32', 'Kab. Garut');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3206', '32', 'Kab. Tasikmalaya');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3207', '32', 'Kab. Ciamis');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3208', '32', 'Kab. Kuningan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3209', '32', 'Kab. Cirebon');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3210', '32', 'Kab. Majalengka');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3211', '32', 'Kab. Sumedang');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3212', '32', 'Kab. Indramayu');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3213', '32', 'Kab. Subang');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3214', '32', 'Kab. Purwakarta');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3215', '32', 'Kab. Karawang');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3216', '32', 'Kab. Bekasi');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3217', '32', 'Kab. Bandung Barat');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3218', '32', 'Kab. Pangandaran');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3271', '32', 'Kota Bogor');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3272', '32', 'Kota Sukabumi');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3273', '32', 'Kota Bandung');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3274', '32', 'Kota Cirebon');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3275', '32', 'Kota Bekasi');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3276', '32', 'Kota Depok');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3277', '32', 'Kota Cimahi');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3278', '32', 'Kota Tasikmalaya');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3279', '32', 'Kota Banjar');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3301', '33', 'Kab. Cilacap');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3302', '33', 'Kab. Banyumas');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3303', '33', 'Kab. Purbalingga');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3304', '33', 'Kab. Banjarnegara');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3305', '33', 'Kab. Kebumen');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3306', '33', 'Kab. Purworejo');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3307', '33', 'Kab. Wonosobo');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3308', '33', 'Kab. Magelang');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3309', '33', 'Kab. Boyolali');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3310', '33', 'Kab. Klaten');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3311', '33', 'Kab. Sukoharjo');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3312', '33', 'Kab. Wonogiri');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3313', '33', 'Kab. Karanganyar');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3314', '33', 'Kab. Sragen');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3315', '33', 'Kab. Grobogan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3316', '33', 'Kab. Blora');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3317', '33', 'Kab. Rembang');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3318', '33', 'Kab. Pati');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3319', '33', 'Kab. Kudus');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3320', '33', 'Kab. Jepara');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3321', '33', 'Kab. Demak');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3322', '33', 'Kab. Semarang');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3323', '33', 'Kab. Temanggung');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3324', '33', 'Kab. Kendal');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3325', '33', 'Kab. Batang');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3326', '33', 'Kab. Pekalongan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3327', '33', 'Kab. Pemalang');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3328', '33', 'Kab. Tegal');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3329', '33', 'Kab. Brebes');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3371', '33', 'Kota Magelang');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3372', '33', 'Kota Surakarta');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3373', '33', 'Kota Salatiga');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3374', '33', 'Kota Semarang');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3375', '33', 'Kota Pekalongan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3376', '33', 'Kota Tegal');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3401', '34', 'Kab. Kulon Progo');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3402', '34', 'Kab. Bantul');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3403', '34', 'Kab. Gunung Kidul');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3404', '34', 'Kab. Sleman');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3471', '34', 'Kota Yogyakarta');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3501', '35', 'Kab. Pacitan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3502', '35', 'Kab. Ponorogo');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3503', '35', 'Kab. Trenggalek');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3504', '35', 'Kab. Tulungagung');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3505', '35', 'Kab. Blitar');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3506', '35', 'Kab. Kediri');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3507', '35', 'Kab. Malang');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3508', '35', 'Kab. Lumajang');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3509', '35', 'Kab. Jember');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3510', '35', 'Kab. Banyuwangi');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3511', '35', 'Kab. Bondowoso');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3512', '35', 'Kab. Situbondo');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3513', '35', 'Kab. Probolinggo');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3514', '35', 'Kab. Pasuruan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3515', '35', 'Kab. Sidoarjo');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3516', '35', 'Kab. Mojokerto');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3517', '35', 'Kab. Jombang');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3518', '35', 'Kab. Nganjuk');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3519', '35', 'Kab. Madiun');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3520', '35', 'Kab. Magetan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3521', '35', 'Kab. Ngawi');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3522', '35', 'Kab. Bojonegoro');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3523', '35', 'Kab. Tuban');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3524', '35', 'Kab. Lamongan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3525', '35', 'Kab. Gresik');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3526', '35', 'Kab. Bangkalan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3527', '35', 'Kab. Sampang');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3528', '35', 'Kab. Pamekasan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3529', '35', 'Kab. Sumenep');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3571', '35', 'Kota Kediri');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3572', '35', 'Kota Blitar');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3573', '35', 'Kota Malang');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3574', '35', 'Kota Probolinggo');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3575', '35', 'Kota Pasuruan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3576', '35', 'Kota Mojokerto');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3577', '35', 'Kota Madiun');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3578', '35', 'Kota Surabaya');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3579', '35', 'Kota Batu');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3601', '36', 'Kab. Pandeglang');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3602', '36', 'Kab. Lebak');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3603', '36', 'Kab. Tangerang');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3604', '36', 'Kab. Serang');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3671', '36', 'Kota Tangerang');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3672', '36', 'Kota Cilegon');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3673', '36', 'Kota Serang');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('3674', '36', 'Kota Tangerang Selatan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('5101', '51', 'Kab. Jembrana');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('5102', '51', 'Kab. Tabanan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('5103', '51', 'Kab. Badung');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('5104', '51', 'Kab. Gianyar');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('5105', '51', 'Kab. Klungkung');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('5106', '51', 'Kab. Bangli');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('5107', '51', 'Kab. Karang Asem');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('5108', '51', 'Kab. Buleleng');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('5171', '51', 'Kota Denpasar');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('5201', '52', 'Kab. Lombok Barat');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('5202', '52', 'Kab. Lombok Tengah');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('5203', '52', 'Kab. Lombok Timur');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('5204', '52', 'Kab. Sumbawa');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('5205', '52', 'Kab. Dompu');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('5206', '52', 'Kab. Bima');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('5207', '52', 'Kab. Sumbawa Barat');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('5208', '52', 'Kab. Lombok Utara');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('5271', '52', 'Kota Mataram');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('5272', '52', 'Kota Bima');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('5301', '53', 'Kab. Sumba Barat');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('5302', '53', 'Kab. Sumba Timur');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('5303', '53', 'Kab. Kupang');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('5304', '53', 'Kab. Timor Tengah Selatan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('5305', '53', 'Kab. Timor Tengah Utara');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('5306', '53', 'Kab. Belu');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('5307', '53', 'Kab. Alor');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('5308', '53', 'Kab. Lembata');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('5309', '53', 'Kab. Flores Timur');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('5310', '53', 'Kab. Sikka');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('5311', '53', 'Kab. Ende');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('5312', '53', 'Kab. Ngada');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('5313', '53', 'Kab. Manggarai');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('5314', '53', 'Kab. Rote Ndao');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('5315', '53', 'Kab. Manggarai Barat');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('5316', '53', 'Kab. Sumba Tengah');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('5317', '53', 'Kab. Sumba Barat Daya');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('5318', '53', 'Kab. Nagekeo');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('5319', '53', 'Kab. Manggarai Timur');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('5320', '53', 'Kab. Sabu Raijua');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('5371', '53', 'Kota Kupang');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6101', '61', 'Kab. Sambas');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6102', '61', 'Kab. Bengkayang');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6103', '61', 'Kab. Landak');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6104', '61', 'Kab. Pontianak');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6105', '61', 'Kab. Sanggau');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6106', '61', 'Kab. Ketapang');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6107', '61', 'Kab. Sintang');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6108', '61', 'Kab. Kapuas Hulu');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6109', '61', 'Kab. Sekadau');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6110', '61', 'Kab. Melawi');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6111', '61', 'Kab. Kayong Utara');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6112', '61', 'Kab. Kubu Raya');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6171', '61', 'Kota Pontianak');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6172', '61', 'Kota Singkawang');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6201', '62', 'Kab. Kotawaringin Barat');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6202', '62', 'Kab. Kotawaringin Timur');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6203', '62', 'Kab. Kapuas');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6204', '62', 'Kab. Barito Selatan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6205', '62', 'Kab. Barito Utara');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6206', '62', 'Kab. Sukamara');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6207', '62', 'Kab. Lamandau');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6208', '62', 'Kab. Seruyan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6209', '62', 'Kab. Katingan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6210', '62', 'Kab. Pulang Pisau');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6211', '62', 'Kab. Gunung Mas');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6212', '62', 'Kab. Barito Timur');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6213', '62', 'Kab. Murung Raya');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6271', '62', 'Kota Palangka Raya');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6301', '63', 'Kab. Tanah Laut');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6302', '63', 'Kab. Kota Baru');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6303', '63', 'Kab. Banjar');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6304', '63', 'Kab. Barito Kuala');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6305', '63', 'Kab. Tapin');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6306', '63', 'Kab. Hulu Sungai Selatan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6307', '63', 'Kab. Hulu Sungai Tengah');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6308', '63', 'Kab. Hulu Sungai Utara');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6309', '63', 'Kab. Tabalong');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6310', '63', 'Kab. Tanah Bumbu');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6311', '63', 'Kab. Balangan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6371', '63', 'Kota Banjarmasin');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6372', '63', 'Kota Banjar Baru');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6401', '64', 'Kab. Paser');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6402', '64', 'Kab. Kutai Barat');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6403', '64', 'Kab. Kutai Kartanegara');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6404', '64', 'Kab. Kutai Timur');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6405', '64', 'Kab. Berau');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6409', '64', 'Kab. Penajam Paser Utara');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6471', '64', 'Kota Balikpapan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6472', '64', 'Kota Samarinda');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6474', '64', 'Kota Bontang');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6501', '65', 'Kab. Malinau');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6502', '65', 'Kab. Bulungan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6503', '65', 'Kab. Tana Tidung');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6504', '65', 'Kab. Nunukan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('6571', '65', 'Kota Tarakan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7101', '71', 'Kab. Bolaang Mongondow');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7102', '71', 'Kab. Minahasa');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7103', '71', 'Kab. Kepulauan Sangihe');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7104', '71', 'Kab. Kepulauan Talaud');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7105', '71', 'Kab. Minahasa Selatan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7106', '71', 'Kab. Minahasa Utara');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7107', '71', 'Kab. Bolaang Mongondow Utara');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7108', '71', 'Kab. Siau Tagulandang Biaro');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7109', '71', 'Kab. Minahasa Tenggara');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7110', '71', 'Kab. Bolaang Mongondow Selatan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7111', '71', 'Kab. Bolaang Mongondow Timur');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7171', '71', 'Kota Manado');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7172', '71', 'Kota Bitung');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7173', '71', 'Kota Tomohon');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7174', '71', 'Kota Kotamobagu');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7201', '72', 'Kab. Banggai Kepulauan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7202', '72', 'Kab. Banggai');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7203', '72', 'Kab. Morowali');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7204', '72', 'Kab. Poso');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7205', '72', 'Kab. Donggala');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7206', '72', 'Kab. Toli-toli');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7207', '72', 'Kab. Buol');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7208', '72', 'Kab. Parigi Moutong');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7209', '72', 'Kab. Tojo Una-una');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7210', '72', 'Kab. Sigi');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7271', '72', 'Kota Palu');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7301', '73', 'Kab. Kepulauan Selayar');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7302', '73', 'Kab. Bulukumba');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7303', '73', 'Kab. Bantaeng');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7304', '73', 'Kab. Jeneponto');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7305', '73', 'Kab. Takalar');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7306', '73', 'Kab. Gowa');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7307', '73', 'Kab. Sinjai');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7308', '73', 'Kab. Maros');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7309', '73', 'Kab. Pangkajene Dan Kepulauan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7310', '73', 'Kab. Barru');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7311', '73', 'Kab. Bone');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7312', '73', 'Kab. Soppeng');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7313', '73', 'Kab. Wajo');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7314', '73', 'Kab. Sidenreng Rappang');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7315', '73', 'Kab. Pinrang');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7316', '73', 'Kab. Enrekang');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7317', '73', 'Kab. Luwu');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7318', '73', 'Kab. Tana Toraja');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7322', '73', 'Kab. Luwu Utara');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7325', '73', 'Kab. Luwu Timur');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7326', '73', 'Kab. Toraja Utara');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7371', '73', 'Kota Makassar');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7372', '73', 'Kota Parepare');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7373', '73', 'Kota Palopo');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7401', '74', 'Kab. Buton');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7402', '74', 'Kab. Muna');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7403', '74', 'Kab. Konawe');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7404', '74', 'Kab. Kolaka');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7405', '74', 'Kab. Konawe Selatan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7406', '74', 'Kab. Bombana');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7407', '74', 'Kab. Wakatobi');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7408', '74', 'Kab. Kolaka Utara');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7409', '74', 'Kab. Buton Utara');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7410', '74', 'Kab. Konawe Utara');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7471', '74', 'Kota Kendari');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7472', '74', 'Kota Baubau');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7501', '75', 'Kab. Boalemo');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7502', '75', 'Kab. Gorontalo');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7503', '75', 'Kab. Pohuwato');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7504', '75', 'Kab. Bone Bolango');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7505', '75', 'Kab. Gorontalo Utara');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7571', '75', 'Kota Gorontalo');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7601', '76', 'Kab. Majene');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7602', '76', 'Kab. Polewali Mandar');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7603', '76', 'Kab. Mamasa');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7604', '76', 'Kab. Mamuju');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('7605', '76', 'Kab. Mamuju Utara');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('8101', '81', 'Kab. Maluku Tenggara Barat');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('8102', '81', 'Kab. Maluku Tenggara');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('8103', '81', 'Kab. Maluku Tengah');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('8104', '81', 'Kab. Buru');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('8105', '81', 'Kab. Kepulauan Aru');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('8106', '81', 'Kab. Seram Bagian Barat');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('8107', '81', 'Kab. Seram Bagian Timur');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('8108', '81', 'Kab. Maluku Barat Daya');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('8109', '81', 'Kab. Buru Selatan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('8171', '81', 'Kota Ambon');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('8172', '81', 'Kota Tual');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('8201', '82', 'Kab. Halmahera Barat');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('8202', '82', 'Kab. Halmahera Tengah');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('8203', '82', 'Kab. Kepulauan Sula');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('8204', '82', 'Kab. Halmahera Selatan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('8205', '82', 'Kab. Halmahera Utara');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('8206', '82', 'Kab. Halmahera Timur');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('8207', '82', 'Kab. Pulau Morotai');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('8271', '82', 'Kota Ternate');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('8272', '82', 'Kota Tidore Kepulauan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('9101', '91', 'Kab. Fakfak');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('9102', '91', 'Kab. Kaimana');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('9103', '91', 'Kab. Teluk Wondama');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('9104', '91', 'Kab. Teluk Bintuni');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('9105', '91', 'Kab. Manokwari');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('9106', '91', 'Kab. Sorong Selatan');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('9107', '91', 'Kab. Sorong');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('9108', '91', 'Kab. Raja Ampat');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('9109', '91', 'Kab. Tambrauw');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('9110', '91', 'Kab. Maybrat');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('9171', '91', 'Kota Sorong');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('9401', '94', 'Kab. Merauke');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('9402', '94', 'Kab. Jayawijaya');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('9403', '94', 'Kab. Jayapura');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('9404', '94', 'Kab. Nabire');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('9408', '94', 'Kab. Kepulauan Yapen');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('9409', '94', 'Kab. Biak Numfor');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('9410', '94', 'Kab. Paniai');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('9411', '94', 'Kab. Puncak Jaya');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('9412', '94', 'Kab. Mimika');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('9413', '94', 'Kab. Boven Digoel');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('9414', '94', 'Kab. Mappi');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('9415', '94', 'Kab. Asmat');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('9416', '94', 'Kab. Yahukimo');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('9417', '94', 'Kab. Pegunungan Bintang');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('9418', '94', 'Kab. Tolikara');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('9419', '94', 'Kab. Sarmi');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('9420', '94', 'Kab. Keerom');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('9426', '94', 'Kab. Waropen');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('9427', '94', 'Kab. Supiori');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('9428', '94', 'Kab. Mamberamo Raya');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('9429', '94', 'Kab. Nduga');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('9430', '94', 'Kab. Lanny Jaya');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('9431', '94', 'Kab. Mamberamo Tengah');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('9432', '94', 'Kab. Yalimo');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('9433', '94', 'Kab. Puncak');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('9434', '94', 'Kab. Dogiyai');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('9435', '94', 'Kab. Intan Jaya');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('9436', '94', 'Kab. Deiyai');
INSERT INTO `wilayah_kabupaten` (`id`, `provinsi_id`, `nama`) VALUES ('9471', '94', 'Kota Jayapura');
